---
title: "Modeling Scenarios for Covid-19"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE
)

```

# Data from: https://github.com/jakobzhao/virus

```{r}
library(tidyverse)
library(tidyquant)
library(crayon)
library(kableExtra)
library(ggrepel)

theme_set(theme_tq())
```



```{r message=TRUE}

# updated every ~4 hours
# cases_data <- suppressMessages(read_csv("http://hgis.uw.edu/virus/assets/virus.csv"))

latest_file <- paste0("hgis virus data/",Sys.Date()," virus.csv")
if(!file.exists(latest_file)){
  
  download.file("http://hgis.uw.edu/virus/assets/virus.csv", destfile = latest_file)
  
}

cases_data <- suppressMessages(read_csv(latest_file))


message("Data from ", min(cases_data$datetime)," to ",max(cases_data$datetime))

```

```{r message=TRUE, warning=FALSE, results = 'asis'}

max_date <- 
  cases_data %>% 
  select(datetime, `new york`) %>% 
  na.omit() %>% summarise(max_date = max(datetime)) %>% 
  pull(max_date)

ny_cases <- 
  cases_data %>% 
  select(datetime, `new york`) %>% 
  na.omit() %>% 
  separate(`new york`, into = c("Confirmed","Suspected","Cured","Deaths")
           , sep = "-", extra = "warn", remove = F) %>% 
  mutate_at(vars(Confirmed:Deaths), as.numeric) %>% 
  mutate(Active = Confirmed+Suspected-Cured-Deaths) %>%
  filter(datetime == max(datetime))



message("Number of confirmed NY cases as of ",max_date,": ", ny_cases$Confirmed,"\n")
message("Number of active NY cases as of ",max_date,": ",ny_cases$Active)

```

# Process case data

```{r message=FALSE, warning=FALSE}

source("00 - Recording NYC Cases.R")
source("04 - Process Case Data.R")

```


# NY State Cases and Deaths 

```{r}
processed %>% 
  filter(area=="new york", !is.na(cases)) %>% 
  select(datetime,Confirmed,Deaths) %>% 
  mutate(Confirmed = c(NA, diff(Confirmed))
         , Deaths = c(NA, diff(Deaths))
         ) %>% 
  gather(Var, Value, -datetime) %>% 
  ggplot()+
  aes(x = datetime, y = Value, group = Var)+
  geom_col()+
  facet_wrap(~Var, ncol = 1, scales = "free_y")+
  theme_tq()

```


# NYC Cases and Deaths

```{r}

NYC_reports %>% 
  select(DATE_OF_INTEREST, NEW_COVID_CASE_COUNT, DEATH_COUNT) %>% 
  gather(Var, Value, -DATE_OF_INTEREST) %>% 
  ggplot()+
  aes(x = DATE_OF_INTEREST, y = Value, fill = Var)+
  geom_col(position = "dodge")+
  geom_smooth(se = F)+
  facet_wrap(~Var, scales = "free_y", ncol = 1)+
  theme_tq()

```


```{r}

NYC_reports %>% 
  select(DATE_OF_INTEREST
         , NEW_COVID_CASE_COUNT_cumulative
         , DEATH_COUNT_cumulative) %>% 
  gather(Var, Value, -DATE_OF_INTEREST) %>% 
  ggplot()+
  aes(x = DATE_OF_INTEREST, y = Value, fill = Var)+
  geom_col(position = "dodge")+
  geom_smooth(se = F)+
  facet_wrap(~Var, scales = "free_y", ncol = 1)+
  theme_tq()

```

# Itlay cases and deaths

```{r}

processed %>% 
  filter(area == "italy") %>% 
  filter(Confirmed>100) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  select(days_since_reported, Confirmed, Deaths) %>% 
  mutate(Confirmed = c(NA,diff(Confirmed))
         , Deaths = c(NA,diff(Deaths))) %>% 
  gather(Var, Value, -days_since_reported) %>% 
  ggplot()+
  aes(x = days_since_reported, y = Value, fill = Var)+
  geom_col(position = "dodge")+
  geom_smooth(se = F)+
  facet_wrap(~Var, scales = "free_y", ncol = 1)+
  theme_tq()

```



# Wuhan cases and deaths

```{r}

processed %>% 
  filter(area == "hubei") %>% 
  filter(Confirmed>100) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  select(days_since_reported, Confirmed, Deaths) %>% 
  mutate(Confirmed = c(NA,diff(Confirmed))
         , Deaths = c(NA,diff(Deaths))) %>% 
  gather(Var, Value, -days_since_reported) %>% 
  ggplot()+
  aes(x = days_since_reported, y = Value, fill = Var)+
  geom_col(position = "dodge")+
  geom_smooth(se = F)+
  facet_wrap(~Var, scales = "free_y", ncol = 1)+
  theme_tq()

```


# NYC cases vs. advanced scenarios: Italy and Chinese provinces

```{r}

source("00 - Recording NYC Cases.R")


processed %>% 
  filter(Country%in%c("China","italy"), area!="hubei") %>%  
  bind_rows(NYC_reports %>% mutate(Country = "NYC")) %>% 
  group_by(area) %>% 
  filter(Confirmed>20) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  ggplot()+
  aes(x = days_since_reported, y = Confirmed, group = area, color = Country)+
  geom_line(size = 2, alpha = 0.6) + 
  theme_tq()+
  scale_color_tq()+
  theme(legend.position = "bottom")+
  scale_y_log10()+
  labs(title = "NYC Covid-19 cases currently tracking closer to Italy than Chinese provinces"
       , y = "Log Scale Count of Confirmed Cases"
       , x = "Days since reaching 20 reported cases"
       , caption = "Source: http://hgis.uw.edu/virus/assets/virus.csv\n NYC data collected by hand")

```

# Deaths

```{r}


processed %>% 
  filter(area%in%c("US","italy")) %>%  
  bind_rows(NYC_reports %>% mutate(Country = "NYC")) %>% 
  group_by(area) %>% 
  filter(Confirmed>20) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  ggplot()+
  aes(x = days_since_reported, y = Deaths, group = area, color = Country)+
  geom_line(size = 2, alpha = 0.6) + 
  theme_tq()+
  scale_color_tq()+
  theme(legend.position = "bottom")+
  labs(title = "Covid-19 deaths NYC vs. Italy"
       , y = "Deceased"
       , x = "Days since reaching 20 reported cases"
       , caption = "Source: http://hgis.uw.edu/virus/assets/virus.csv\n NYC data collected by hand")

```

# Log deaths

```{r}


processed %>% 
  filter(area%in%c("US","italy", "hubei")) %>%  
  bind_rows(NYC_reports %>% mutate(Country = "NYC")) %>% 
  group_by(area) %>% 
  filter(Deaths>10) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  mutate(Deaths = log(Deaths)) %>%
  ggplot()+
  aes(x = days_since_reported, y = Deaths, group = area, color = area)+
  geom_line(size = 2, alpha = 0.6) + 
  theme_tq()+
  scale_color_tq()+
  #scale_y_log10()+
  theme(legend.position = "bottom")+
  labs(title = "Covid-19 deaths NYC, Italy, Wuhan"
       , y = "Deceased, log scale"
       , x = "Days since reaching 10 reported deaths"
       , caption = "Source: http://hgis.uw.edu/virus/assets/virus.csv\n NYC data collected by hand")

```


```{r}

processed %>% 
  filter(Country%in%c("China","italy"), area!="hubei") %>%  
  bind_rows(NYC_reports %>% mutate(Country = "NYC")) %>% 
  arrange(desc(Country)) %>% 
  group_by(area) %>% 
  filter(Confirmed>20) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  filter(days_since_reported<20) %>% 
  ggplot()+
  aes(x = days_since_reported, y = Confirmed, group = area, color = Country)+
  geom_line(size = 2, alpha = 0.5) + 
  theme_tq()+
  scale_color_tq()+
  theme(legend.position = "bottom")+
 labs(title = "NYC Covid-19 cases days 1-20"
       , y = "(Actual) Count of Confirmed Cases"
       , x = "Days since reaching 20 reported cases"
       , caption = "Source: http://hgis.uw.edu/virus/assets/virus.csv\n NYC data collected by hand")

```


```{r}
library(DT)
NYC_reports %>%
  datatable(options = list(paging = F, searching = F))


```




# US States

```{r US states}
processed %>% 
  filter(area%in% us_state_names) %>% 
  group_by(area) %>% 
  filter(Confirmed>100) %>% 
  mutate(days_since_reported = 1:n()) %>% 
   mutate(label = if_else(days_since_reported == max(days_since_reported) & 
                            Confirmed>5000
                         , as.character(area), NA_character_)) %>%
  ggplot()+
  aes(x = days_since_reported, y = Confirmed, color = area)+
  geom_line(size = 1)+
  geom_label_repel(aes(label = label),
                   nudge_x = 1,
                   na.rm = TRUE) +
  theme_tq()+
  theme(legend.position = "none")+
  scale_color_tq(theme = "light")+
  labs(x = "Days since reaching 20 cases"
       , y = "Confirmed Cases")

```


```{r US states log}
processed %>% 
  filter(area%in% us_state_names) %>% 
  group_by(area) %>% 
  filter(Confirmed>20) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  ggplot()+
  aes(x = days_since_reported, y = Confirmed, color = area)+
  geom_line(size = 1)+
  theme_tq()+
  scale_color_tq(theme = "light")+
  scale_y_log10()+
  labs(x = "Days since reaching 20 cases"
       , y = "Confirmed Cases log scale")

```




# Active Cases

```{r days since reported}

processed %>% 
  filter(Country!="Other") %>% 
  filter(Active>20) %>% 
  group_by(area) %>% 
  mutate(days_since_reported=1:n()) %>% 
  mutate(label = ifelse(days_since_reported==max(days_since_reported) & 
                            Active>2000, area, NA_character_)) %>% 
  ggplot()+
  aes(x = days_since_reported, y = Active, group = area, label = area, color = Country)+
  geom_line()+
  
  geom_text(aes(label = label))+
  scale_color_tq()+
  theme_tq()+
  theme(legend.position = "none")+
  theme(plot.title.position = "plot")+
  labs(title = "Active Cases Worldwide"
       , x = "days since reacing 20 active cases")

```

# Active Cases Per 1M People

```{r}
populations_2015 <- 
  read_csv("data/UN-population-projection-medium-variant.csv") %>% 
  filter(Year==2015) %>% 
  select(Entity, "Population" = `Estimates, 1950 - 2015: Total population by broad age group, both sexes combined (thousands) - Total`) %>% 
  mutate(Population_1M = Population/1000000) %>% 
  mutate(Entity = str_to_lower(Entity)) %>% 
  mutate(Entity = case_when(
    Entity == "united states" ~ "us"
    , TRUE ~ Entity
  ))

processed %>% 
  filter(Country!="Other") %>% 
  filter(Active>500) %>% 
  group_by(area) %>% 
  mutate(days_since_reported=1:n()) %>% 
  mutate(label = ifelse(days_since_reported==max(days_since_reported) #& Active>2000
                        , area, NA_character_)) %>% 
  inner_join(populations_2015, by = c(area = "Entity")) %>% 
  mutate(Active_per_1M_people = Active / Population_1M) %>% 
  ggplot()+
  aes(x = days_since_reported
      , y = Active_per_1M_people
      , group = area, label = area, color = area)+
  geom_line()+
  geom_text(aes(label = label))+
  scale_color_tq()+
  theme_tq()+
  theme(legend.position = "none")+
  theme(plot.title.position = "plot")+
  labs(title = "Active Cases Per 1 Million People"
       , x = "days since reacing 500 active cases"
       , y = "Active cases per 1 million people")



```


# Most advanced cases - Chinese Provinces


```{r}

processed %>% 
  filter(Country=="China", area!="hubei") %>% 
  ggplot()+
  aes(x = days_since_reported, y = Active, group = area, label = area, color = Country)+
  geom_line()

```

# US

```{r US}
processed %>% 
  filter(Country=="US") %>% 
  ggplot()+
  aes(x = days_since_reported, y = Confirmed, color = area)+
  geom_line()

```



# Western Countries

```{r Western Countries}

processed %>% 
  filter(area%in% c("us","italy","canada","france","australia"
                    ,"germany","israel","uk","greece","spain", "china")) %>% 
  group_by(area) %>% 
  filter(Confirmed>20) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  mutate(label = if_else(days_since_reported == max(days_since_reported) 
                         , as.character(area), NA_character_)) %>%
  ggplot()+
  aes(x = days_since_reported, y = Active, color = area)+
  geom_line()+
  geom_label_repel(aes(label = label),
                   nudge_x = 1,
                   na.rm = TRUE) +
  theme_tq()+
  scale_color_tq()+
  labs(x = "Days since reaching 20 cases"
       , y = "Active Cases")

```

```{r Western Countries log}

processed %>% 
  filter(area%in% c("us","canada","france","australia","germany","israel","spain","italy")) %>% 
  group_by(area) %>% 
  filter(Confirmed>20) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  mutate(label = if_else(days_since_reported == max(days_since_reported) #& Active>500
                         , as.character(area), NA_character_)) %>%
  ggplot()+
  aes(x = days_since_reported, y = Active, color = area)+
  geom_line()+
  geom_label_repel(aes(label = label),
                   nudge_x = 1,
                   na.rm = TRUE) +
  theme_tq()+
  scale_color_tq()+
  scale_y_log10()+
  labs(x = "Days since reaching 20 cases"
       , y = "Active Cases Log Scale")

```


# New York State

```{r NYC}

processed %>% 
  filter(area %in% "new york") %>% 
  filter(!is.na(cases)) %>% 
  ggplot()+
  aes(x = datetime, y = Active, color = area)+
  geom_line()

```


# MODELING

```{r modeling, eval=FALSE, include=F}

library(modelr)

not_na_processed <- 
  processed %>% 
  mutate(Country = as.factor(Country)) %>% 
  filter(!is.na(days_since_reported)) %>% 
  group_by(area) %>% 
  filter(Active>20) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  ungroup() %>% 
  select(-c(first_reported, cases, Confirmed:Deaths)) 

country_model <- function(data){
  loess(Active~days_since_reported
        , data = data
        #, control = loess.control(surface = "direct")
  )    
}

model_all <- not_na_processed %>% country_model()

model_western <- not_na_processed %>% 
  filter(Country%in% c("US","canada","france","australia","germany","israel")) %>% 
  country_model()

model_us_states <- not_na_processed %>% 
  filter(area %in% us_state_names) %>% 
  country_model()

model_japan <- not_na_processed %>% 
  filter(area=='japan') %>% 
  country_model()

model_italy <- not_na_processed %>% 
  filter(area=='italy') %>% 
  country_model()

model_china_ex_wuhan <- not_na_processed %>% 
  filter(Country=='China', area != "hubei") %>% 
  country_model()

model_france <- not_na_processed %>% 
  filter(Country=='france') %>% 
  country_model()

model_germany <- not_na_processed %>% 
  filter(Country=='germany') %>% 
  country_model()


actual_nyc <- 
  not_na_processed %>% 
  filter(area=="new york") %>% 
  filter(days_since_reported>0) %>% 
  select(days_since_reported, "Actual Active" = Active) %>% 
  mutate(model = "Actual Active") 

max_days <- actual_nyc %>% 
  summarise(days = max(days_since_reported)) %>% 
  pull(days)



not_na_processed %>% 
  group_by(area) %>% 
  filter(Active>20) %>% 
  mutate(days_since_reported = 1:n()) %>% 
  ungroup() %>% 
  data_grid(area, days_since_reported) %>% 
  filter(area=="new york") %>% 
  
  
  add_predictions(model_all, var = "world model") %>%
  add_predictions(model_japan, var = "japan model") %>%
  add_predictions(model_china_ex_wuhan, var = "china model") %>%
  add_predictions(model_france, var = "france model") %>%
  add_predictions(model_germany, var = "germany model") %>%
  
  
  
  gather(model, prediction, -area, -days_since_reported) %>% 
  ggplot()+
  aes(days_since_reported, y = prediction, color = model)+
  geom_line(size = 1)+
  geom_line(data = actual_nyc, aes(y = `Actual Active`), linetype = 1, size = 2)+
  geom_vline(xintercept = max_days, color = "black", size = 1)+
  theme_tq()+
  scale_color_tq()+
  labs(title = "New York City Active Case Scenarios"
       , subtitle = "black line denotes NYC actual days since reported"
       , y = "Predicted Active Cases"
       , x = "Days since reacihng 20 reported cases")




```




